"use client";
import { Card, CardBody, CardHeader, CardTitle, Badge } from "./ui/primitives";
import type { SignalCard, Evidence, Scores } from "@/lib/types";
import { ShieldCheck } from "lucide-react";

const SIGNAL_WEIGHTS: Record<string, Record<string, number>> = {
  hiring:     { "Why-Now": 0.18, "Buying Intent": 0.25, "Expansion": 0.10 },
  funding:    { "Why-Now": 0.22, "Buying Intent": 0.20, "Expansion": 0.20 },
  product:    { "Why-Now": 0.18, "Expansion": 0.22 },
  news:       { "Why-Now": 0.10, "Expansion": 0.08 },
  competitor: { "Competitor Threat": 0.35, "Why-Now": 0.08 },
  pricing:    { "Competitor Threat": 0.18, "Why-Now": 0.05 },
  review:     { "Competitor Threat": 0.10, "Buying Intent": 0.05 },
  expansion:  { "Expansion": 0.22, "Why-Now": 0.10 },
};

export function AuditTrail({
  signals,
  evidence,
}: {
  signals: SignalCard[];
  evidence: Evidence[];
  scores: Scores;
}) {
  const byId = Object.fromEntries(evidence.map((e) => [e.id, e]));

  return (
    <Card>
      <CardHeader className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-3">
          <CardTitle>Scoring Audit Trail</CardTitle>
          <Badge tone="positive">
            <ShieldCheck className="h-3 w-3" />
            deterministic
          </Badge>
        </div>
        <div className="text-[11px] text-ink-muted">
          Score computed in <span className="font-mono text-ink-dim">scoring.py</span> — not generated by Claude
        </div>
      </CardHeader>
      <CardBody className="p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-bg-elev/60 text-ink-muted text-[11px] uppercase tracking-wider border-b border-line">
              <tr>
                <th className="text-left font-normal px-4 py-2.5">Signal</th>
                <th className="text-left font-normal px-4 py-2.5">Impact</th>
                <th className="text-left font-normal px-4 py-2.5">Sources</th>
                <th className="text-left font-normal px-4 py-2.5">Live</th>
                <th className="text-left font-normal px-4 py-2.5">Tool</th>
                <th className="text-left font-normal px-4 py-2.5">Score weights</th>
                <th className="text-left font-normal px-4 py-2.5">AI role</th>
                <th className="text-left font-normal px-4 py-2.5">Conf.</th>
              </tr>
            </thead>
            <tbody>
              {signals.map((sig) => {
                const items = sig.evidence_ids.map((id) => byId[id]).filter(Boolean);
                const liveCount = items.filter((e) => e.mode === "live").length;
                const tools = [...new Set(items.map((e) => e.tool))];
                const weights = SIGNAL_WEIGHTS[sig.kind] ?? {};
                const weightStr = Object.entries(weights)
                  .map(([dim, w]) => `${dim} ${w}`)
                  .join("  ·  ");
                const conf = _avgConf(items.map((e) => e.confidence));

                return (
                  <tr
                    key={sig.title}
                    className="border-t border-line/60 hover:bg-bg-elev/30 transition-colors"
                  >
                    <td className="px-4 py-3 max-w-[180px]">
                      <div className="text-[12.5px] text-ink font-medium leading-tight">
                        {sig.title}
                      </div>
                      <div className="text-[10px] text-ink-dim uppercase tracking-wider mt-0.5">
                        {sig.kind}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <Badge
                        tone={
                          sig.impact === "positive"
                            ? "positive"
                            : sig.impact === "negative"
                            ? "danger"
                            : "neutral"
                        }
                      >
                        {sig.impact}
                      </Badge>
                    </td>
                    <td className="px-4 py-3 text-[13px] text-ink-muted">{items.length}</td>
                    <td className="px-4 py-3">
                      {liveCount > 0 ? (
                        <span className="text-[13px] text-accent font-semibold">{liveCount}</span>
                      ) : (
                        <span className="text-[13px] text-ink-dim">0</span>
                      )}
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex flex-col gap-1">
                        {tools.length > 0 ? (
                          tools.map((t) => (
                            <Badge key={t} tone="info">
                              {t}
                            </Badge>
                          ))
                        ) : (
                          <span className="text-[10px] text-ink-dim">—</span>
                        )}
                      </div>
                    </td>
                    <td className="px-4 py-3 font-mono text-[10px] text-ink-muted max-w-[180px]">
                      {weightStr || "—"}
                    </td>
                    <td className="px-4 py-3">
                      <div className="text-[11px] text-ink-muted">Title only</div>
                      <div className="text-[10px] text-accent mt-0.5">score is deterministic</div>
                    </td>
                    <td className="px-4 py-3">
                      <Badge
                        tone={
                          conf === "high"
                            ? "positive"
                            : conf === "medium"
                            ? "info"
                            : "warn"
                        }
                      >
                        {conf}
                      </Badge>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div className="px-4 py-3 border-t border-line/60 text-[11px] text-ink-dim bg-bg-elev/30">
          Each row maps to evidence in the ledger above. Signal weights are defined in{" "}
          <span className="font-mono text-ink-muted">backend/app/services/scoring.py</span>.
          Claude synthesized signal titles — it did not generate any numeric score.
        </div>
      </CardBody>
    </Card>
  );
}

function _avgConf(levels: string[]): "low" | "medium" | "high" {
  if (!levels.length) return "low";
  const order: Record<string, number> = { low: 1, medium: 2, high: 3 };
  const avg = levels.reduce((s, l) => s + (order[l] ?? 1), 0) / levels.length;
  return avg >= 2.5 ? "high" : avg >= 1.6 ? "medium" : "low";
}
